import{a as g,i,S as m}from"./assets/vendor-32598135.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const u=async(t,r)=>{const s="https://pixabay.com/api/",a="42512017-1bddfdd3afd2851258a10c68c",e=t;await g.get(`${s}?key=${a}&q=${e}`,{params:{image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15}}).then(o=>{h(o.data,t,r)}).catch(o=>i.error({class:"popup-message",theme:"dark",backgroundColor:"#ef4040",messageColor:"#fff",iconUrl:Error,position:"topRight",pauseOnHover:!0,timeout:3e3,message:`${o}`}))},p=new m(".gallery a",{spinner:!1,overlayOpacity:.8}),f=()=>{const t=document.querySelector(".gallery__list").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2+48,left:0,behavior:"smooth"})},c=(t,r,s)=>{const a=document.querySelector(".gallery");if(t){a.insertAdjacentHTML("beforeend",'<button class="gallery__action" type="button">Load more</button>');const e=a.querySelector(".gallery__action");e.addEventListener("click",()=>{s+=1,e.remove(),n(!0),setTimeout(async()=>{await u(r,s),f()},500)})}else{const e=a.querySelector(".gallery__action");if(!e)return;e.remove()}},y=(t,r,s)=>{const a=[...document.querySelectorAll(".gallery__item")],e=document.querySelector(".gallery__action"),o=document.querySelector(".gallery");!a.length||e||(a.length<t?c(!0,r,s):(c(!1),o.insertAdjacentHTML("beforeend",`<p class="gallery__meassage">We're sorry, but you've reached the end of search results.</p>`)))},n=t=>{const r=document.querySelector(".gallery");if(t)r.insertAdjacentHTML("beforeend",'<div class="loader"></div>');else{const s=r.querySelector(".loader");if(!s)return;s.remove()}},_=()=>{const t=document.querySelector(".gallery__list");if(!t)return;t.innerHTML="";const r=document.querySelector(".gallery__meassage");r&&r.remove()},h=({hits:t,totalHits:r},s,a)=>{const e=document.querySelector(".gallery__list");if(!e)return;t.length||(i.error({class:"popup-message",theme:"dark",backgroundColor:"#ef4040",messageColor:"#fff",iconUrl:Error,position:"topRight",pauseOnHover:!0,timeout:3e3,message:"Sorry, there are no images matching your search query. Please, try again!"}),n(!1));const o=[];t.map(l=>{const d=`<li class="gallery__item">
      <div class="gallery-card">
        <a class="gallery-card__link" href="${l.largeImageURL}" aria-label="Open image in modal">
          <img class="gallery-card__image" src="${l.webformatURL}" alt="${l.tags}">
        </a>
        <div class="gallery-card__caption">
          <p class="gallery-card__text">Likes <span>${l.likes}</span></p>
          <p class="gallery-card__text">Views <span>${l.views}</span></p>
          <p class="gallery-card__text">Comments <span>${l.comments}</span></p>
          <p class="gallery-card__text">Downloads <span>${l.downloads}</span></p>
        </div>
      </div>
    </li>`;o.push(d)}),n(!1),e.insertAdjacentHTML("beforeend",o.join("")),p.refresh(),y(r,s,a)},v=()=>{const t=document.querySelector(".form"),r=t.querySelector(".form__input");!t||!r||t.addEventListener("submit",s=>{if(s.preventDefault(),!r.value.length)return;const a=r.value.trim().split(" ").join("+");_(),n(!0),c(!1,a),setTimeout(()=>{u(a,1)},500),r.value=""})};document.addEventListener("DOMContentLoaded",()=>{v()});
//# sourceMappingURL=commonHelpers.js.map
