import{a as d,S as f,i}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const m="https://pixabay.com/api/",g="42512017-1bddfdd3afd2851258a10c68c",y=async(a,r)=>(await d.get(`${m}?key=${g}&q=${a}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${per_page}&page=${r}`,{params:{image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15}})).data,h=new f(".gallery a",{captionsData:"alt",captionDelay:250}),p=document.querySelector('button[type="submit"]'),l=document.querySelector(".images-list"),_=document.querySelector(".js-form"),b=document.querySelector('input[name="js-input"]'),c=document.querySelector(".loader");c.style.display="none";_.addEventListener("submit",L);function L(a){a.preventDefault(),c.style.display="block";const r=a.currentTarget.elements["js-input"].value;r?y(r,1).then(s=>{s.total===0?i.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"rgb(239, 64, 64)"}):(l.innerHTML="",l.insertAdjacentHTML("beforeend",v(s.hits)),h.refresh())}).catch(s=>{console.log(s),i.error({class:"popup-message",theme:"dark",backgroundColor:"#ef4040",messageColor:"#fff",iconUrl:Error,position:"topRight",pauseOnHover:!0,timeout:3e3,message:`${s}`})}).finally(()=>{c.style.display="none"}):(p.disabled=!0,i.show({message:"Please, enter the value!"}))}function v(a){return a.map(({webformatURL:r,largeImageURL:s,tags:n,likes:e,views:t,comments:o,downloads:u})=>`<li class="gallery__item">
        <div class="gallery__card">
          <a href="${s}" class="gallery-card__link"
            ><img src="${r}" alt="${n}" class="gallery-card__image"
          /></a>
          <div class="gallery-card__description">
            <p class="gallery-card__text">Likes <span>${e}</span></p>
            <p class="gallery-card__text">Views <span>${t}</span></p>
            <p class="gallery-card__text">Comments <span>${o}</span></p>
            <p class="gallery-card__text">Downloads <span>${u}</span></p>
          </div>
        </div>
      </li>`).join("")}b.addEventListener("input",function(){p.disabled=!1});l.addEventListener("click",function(a){a.preventDefault()});
//# sourceMappingURL=commonHelpers.js.map
